### ISSUE TITLE
Upload function is not handling dates properly in current version of database connector

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#343]
Dates are not handled properly by upload function

This is fixed in unreleased version of database connector
related to https://github.com/OHDSI/DatabaseConnector/issues/137

> 
> |                                                                                                                                |   0%java.sql.BatchUpdateException: Batch entry 0 INSERT INTO test.concept (concept_id,concept_name,domain_id,vocabulary_id,concept_class_id,standard_concept,concept_code,valid_start_date,valid_end_date,invalid_reason) VALUES(3021537,'Insulin [Mass/volume] in Serum or Plasma --30 minutes post dose tolbutamide IV','Measurement','LOINC','Lab Test','S','1565-1',0.0,47481.0,NULL) was aborted: ERROR: column "valid_start_date" is of type date but expression is of type double precision
>   Hint: You will need to rewrite or cast the expression.
>   Position: 198  Call getNextException to see other errors in the batch.
> 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:169)
> 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:854)
> 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:893)
> 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
> 	at org.ohdsi.databaseConnector.BatchedInsert.executeBatch(BatchedInsert.java:114)
> Caused by: org.postgresql.util.PSQLException: ERROR: column "valid_start_date" is of type date but expression is of type double precision
>   Hint: You will need to rewrite or cast the expression.
>   Position: 198
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
> 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
> 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
> 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:851)
> 	... 3 more
> ERROR: column "valid_start_date" is of type date but expression is of type double precision
>   Hint: You will need to rewrite or cast the expression.
>   Position: 198

**Comment by gowthamrao** [comment]
Fixed with updated database connector
