### ISSUE TITLE
Observation Period Calculation data type issue for person days calculation

### ISSUE THREAD

**Issue by mdlavallee92** [OHDSI/CohortDiagnostics#841]
Hello,

I have run into an issue a few times now with network studies where study nodes get an error in cohort diagnostics from the following code in the main execution function (L478:491): 

```
  ## Observation period----
  ParallelLogger::logTrace(" - Collecting date range from Observational period table.")
  observationPeriodDateRange <- renderTranslateQuerySql(
    connection = connection,
    sql = "SELECT MIN(observation_period_start_date) observation_period_min_date,
             MAX(observation_period_end_date) observation_period_max_date,
             COUNT(distinct person_id) persons,
             COUNT(person_id) records,
             SUM(DATEDIFF(dd, observation_period_start_date, observation_period_end_date)) person_days 
             FROM @cdm_database_schema.observation_period;",
    cdm_database_schema = cdmDatabaseSchema,
    snakeCaseToCamelCase = TRUE,
    tempEmulationSchema = tempEmulationSchema
  )
```

Cohort diagnostic fails because of the person days calculation has a number greater than what can be handled by INT. Can this be cast to bigint? 

Here is an example of where it has failed (thanks @mgkahn for pointing this out):

Database: BigQuery
Saw same error also from cohortDiagnostics in COVID AE project. Required explicit CAST to INT64 somewhere in the bowels of CohortDiagnostics that must not have made it to the version being pulled for this project.

Michael Kahn

```
#Step 3 -- Run cohortDiagnostics

#execute cohort diagnostics
CohortDiagnostics::executeDiagnostics(cohortDefinitionSet = cohortDefinitionSet, .... [TRUNCATED]
Run Cohort Diagnostics started at 2022-06-27 17:08:29
Connecting using BigQuery driver
Saving database metadata
Saving database metadata took 0.163 secs
Counting cohort records and subjects
Counting cohorts took 1.48 secs

Censoring 0 values (0%) from cohortEntries because value below minimum
Censoring 0 values (0%) from cohortSubjects because value below minimum
Found 7 of 7 (100.00%) submitted cohorts instantiated. Beginning cohort diagnostics for instantiated cohorts.
Fetching inclusion statistics from files
Exporting inclusion rules with CohortGenerator
Inserting inclusion rule names
java.sql.SQLException: [Simba][BigQueryJDBCDriver](https://github.com/ohdsi-studies/ReproducibilityRayJAMA2021/issues/100032) Error executing query job. Message: Value has type FLOAT64 which cannot be inserted into column rule_sequence, which has type INT64 at [1:139]
at com.simba.googlebigquery.googlebigquery.client.BQClient$2.throwException(Unknown Source)
at com.simba.googlebigquery.googlebigquery.client.BQClient$RequestWithRetry.executeWithRetry(Unknown Source)
at com.simba.googlebigquery.googlebigquery.client.BQClient.executeQuery(Unknown Source)
at com.simba.googlebigquery.googlebigquery.dataengine.BQAbstractExecutor.execute(Unknown Source)
at com.simba.googlebigquery.googlebigquery.dataengine.BQSQLExecutor.execute(Unknown Source)
at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executeWithParams(Unknown Source)
at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executeAnyUpdate(Unknown Source)
at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executeUpdate(Unknown Source)
Caused by: com.simba.googlebigquery.support.exceptions.GeneralException: [Simba][BigQueryJDBCDriver](https://github.com/ohdsi-studies/ReproducibilityRayJAMA2021/issues/100032) Error executing query job. Message: Value has type FLOAT64 which cannot be inserted into column rule_sequence, which has type INT64 at [1:139]
... 8 more
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
GET https://bigquery.googleapis.com/bigquery/v2/projects/hdcohdsihghmk/queries/SimbaJDBC_Job_54c0fcfa-fd98-41e6-8d44-2c36093f411f?location=US&maxResults=10000&timeoutMs=50000000
{
"code": 400,
"errors": [
{
"domain": "global",
"location": "q",
"locationType": "parameter",
"message": "Value has type FLOAT64 which cannot be inserted into column rule_sequence, which has type INT64 at [1:139]",
"reason": "invalidQuery"
}
],
"message": "Value has type FLOAT64 which cannot be inserted into column rule_sequence, which has type INT64 at [1:139]",
"status": "INVALID_ARGUMENT"
}
at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
at com.simba.googlebigquery.googlebigquery.client.BQClient$2.execute(Unknown Source)
at com.simba.googlebigquery.googlebigquery.client.BQClient$RequestWithRetry.executeWithRetry(Unknown Source)
at com.simba.googlebigquery.googlebigquery.client.BQClient.executeQuery(Unknown Source)
at com.simba.googlebigquery.googlebigquery.dataengine.BQAbstractExecutor.execute(Unknown Source)
at com.simba.googlebigquery.googlebigquery.dataengine.BQSQLExecutor.execute(Unknown Source)
at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executeWithParams(Unknown Source)
at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executeAnyUpdate(Unknown Source)
at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executeUpdate(Unknown Source)
at org.ohdsi.databaseConnector.BatchedInsert.executeBigQueryBatch(BatchedInsert.java:157)
Fetching data from cohort_inclusion_CU_AMC_Colorado_rayJama
Fetching data from cohort_inclusion_result_CU_AMC_Colorado_rayJama
Fetching data from cohort_inclusion_stats_CU_AMC_Colorado_rayJama
Fetching data from cohort_summary_stats_CU_AMC_Colorado_rayJama
Fetching data from cohort_censor_stats_CU_AMC_Colorado_rayJama
```

**Comment by azimov** [comment]
Hi @mdlavallee92, thanks for filing this issue. Casting the date diff as bigint should work, however, I don't have access to a big query database to test this.

Running the lines you pointed out with the proposed modification should test if this fix resolves the issue:


```{r}
  observationPeriodDateRange <- renderTranslateQuerySql(
    connection = connection,
    sql = "SELECT MIN(observation_period_start_date) observation_period_min_date,
             MAX(observation_period_end_date) observation_period_max_date,
             COUNT(distinct person_id) persons,
             COUNT(person_id) records,
             SUM(CAST(DATEDIFF(dd, observation_period_start_date, observation_period_end_date) AS BIGINT)) person_days
             FROM @cdm_database_schema.observation_period;",
    cdm_database_schema = cdmDatabaseSchema,
    snakeCaseToCamelCase = TRUE,
    tempEmulationSchema = tempEmulationSchema
  )
```

If this works, we should be able to hot fix pretty quickly.

**Comment by mdlavallee92** [comment]
I tested this code block, it worked without errors in bigquery. This should be the fix.

**Comment by azimov** [comment]
This has now been fixed in the latest hotfix release.
